services:
  - type: web
    name: chatbot-onboarding
    runtime: python
    buildCommand: ""
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PORT
        value: 10000
    plan: free
services:
  - type: web
    name: ringai-app
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python -m spacy download en_core_web_sm
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    plan: free
    region: oregon
